### PR TITLE
Indexed jump to the opted function

### PR DESCRIPTION
**Pull request by isoux**
Beautifully arranged `b_system_table:`

Thank You!

### CODE REVIEW

**Comment by IanSeyler** [comment]
Ok one issue I've noticed is `systest.app` cannot execute the SMP test anymore. The RCX register is not being preserved when `b_system` is called. Looking into a way around this. We may need to `push rcx` and have all `b_system` calls return back to `b_system_end` so it can do a `pop rcx` there.

**Comment by IanSeyler** [comment]
I've updated the `b_system` branch to use push/pop for RCX. It works properly.

**Comment by isoux** [comment]
I think this is a [simpler](https://github.com/isoux/BareMetal/commit/797f20d7e891bf2ed8862ead22205b9e9f50194a) solution, without introducing new jmp and ret instructions...
Always save the index of the called function (in memory) and use it only when needed?

I checked the code and it works now, you can certainly do better because you know the whole system.

**Comment by IanSeyler** [comment]
That would work as long as two or more CPU cores don't call `b_system` at the exact same time. There is a small possibility that the value in `[b_system_function]` gets overwritten by another core. A mutex could be added but I'd rather not lock `b_system` behind one.

**Comment by IanSeyler** [comment]
Looks good!

There is just one fix to be made. The `push rcx` needs to be after the `cmp` and `jg`.

If you repeatedly call `b_system` with `RCX` being greater than `0xFF` then you could overflow the stack.

I updated my branch to show that.

**Comment by isoux** [comment]
Another [solution](https://github.com/ReturnInfinity/BareMetal/pull/85/commits/acb47ec53eecffbf76888045cf25eee110a3c281): call function from the stack! 
No more taking RCX reg at stack (just inside the functions). 

Just one rygly thing: variable for empting the stack...

**Comment by isoux** [comment]
IF 
```
cmp rcx, 0xFF
jg b_system_end
```
THEN
```
b_system_end:
	pop rcx
	ret
```
How are you going to POP RCX when you don't PUSH it anywhere for the case when RCX is greater than 0xFF?

**Comment by IanSeyler** [comment]
Yep - my bad. I read the code incorrectly.

Your code is good:
```
; To save memory, the functions are placed in 16-bit frames
	push rcx
	lea ecx, [b_system_table+ecx*2]	; extract function from table by index
	mov cx, [ecx]			; limit jump to 16-bit
	call rcx			; call function
        pop rcx

b_system_end:
	ret
```

**Comment by isoux** [comment]
No problem!

What are you saying for Another [solution](https://github.com/ReturnInfinity/BareMetal/pull/85/commits/acb47ec53eecffbf76888045cf25eee110a3c281): call function from the stack!

**Comment by isoux** [comment]
> Another [solution](https://github.com/ReturnInfinity/BareMetal/pull/85/commits/acb47ec53eecffbf76888045cf25eee110a3c281): call function from the stack! No more taking RCX reg at stack (just inside the functions).
> 
> Just one rygly thing: variable for empting the stack...

**Comment by isoux** [comment]
Great,
If the final code is merged in your branch and if you agree I will copy it and do another final PR I would like to be merged it by your side tell me what the commit message should be?

**Comment by IanSeyler** [comment]
My branch is up to date. You can copy it to your merge.

As for the commit message: "Rework `b_system` to use a index table instead of checking the value of `CL` multiple times"

**Comment by isoux** [comment]
It's done!

**Review by IanSeyler — APPROVED** [review]
Looks good!

**Comment by isoux** [comment]
I am very happy!

I'm glad I could help, and also in the future too.
You made my day man!

**Comment by IanSeyler** [comment]
Awesome work there. It's much better than previous version with all those `cmp`'s

**Comment by isoux** [comment]
It is very important that system functions are detected and executed as quickly as possible. 
If there are other similar bottlenecks in the system, please highlight them if we can speed them up?

**Comment by IanSeyler** [comment]
The `b_system` function won't be called often so performance isn't much of a concern. It's the disk and network I/O functions that need the most performance and those have their own entry point at the start of `kernel.asm`

**Pull request merged**
